### PR TITLE
macOS build info

### PR DESCRIPTION
**Pull request by kapitainsky**

### CODE REVIEW

**Comment by kapitainsky** [comment]
I will still do some editing - so I let you know when it is ready

**Comment by deajan** [comment]
Thank you, I'll merge once you're done

**Comment by kapitainsky** [comment]
ok - now I am happy with my edits. Done.

**Comment by deajan** [comment]
Again, thanks for your time.
Hopefully I can get hands on a macOS VM in order to have prebuilt executables for darwin.

Btw, I noticed you wrote both for intel and arm archs.
What devices use arm processors with macOS ? I'm quite puzzled.

**Comment by kapitainsky** [comment]
> Again, thanks for your time.
> Hopefully I can get hands on a macOS VM in order to have prebuilt executables for darwin.

Thank you this software. I wish it success:)

**Comment by kapitainsky** [comment]
> Btw, I noticed you wrote both for intel and arm archs.
> What devices use arm processors with macOS ? I'm quite puzzled.

hahaha - all Apple devices use ARM now... it is yet another Apple transition - like before from PowerPC to Intel. They make their own CPUs nowadays and they live Intel far behind

Intel is legacy platform but only fully replaced by ARM this month - so will be in use for the next few years

**Comment by kapitainsky** [comment]
it is possible to build so called universal binaries - which work on both platforms - but I am not sure how it would work with Python. Some software vendors provide universal binaries and some split to Intel and ARM.

**Comment by kapitainsky** [comment]
Also if you would need any testing on macOS etc. - just let me know

**Pull request merged**
