### PR TITLE
missing dependency - imageio

### PR DESCRIPTION
**Pull request by kapitainsky**

### CODE REVIEW

**Comment by deajan** [comment]
Must be a MacOS only dependency, that comes with PySimpleGUI.
When only used on a specific platform, we need to add `; platform_system == "Platform"` in the corresponding `requirements.txt`  line.
In our case `imageio; platform_system == "Darwin"`

Would you mind running `python -c "import platform; print(platform.system())"` so me make sure this resolves to "Darwin" (with the capitalization) ?

**Comment by kapitainsky** [comment]
Ok - will fix it

**Comment by deajan** [comment]
Thank you for your time ;)

**Comment by kapitainsky** [comment]
narrowed requirement of `` 

> Would you mind running `python -c "import platform; print(platform.system())"` so me make sure this resolves to "Darwin" (with the capitalization) ?

all good:

```
% /usr/local/bin/python3  -c "import platform; print(platform.system())"
Darwin
```

**Pull request merged**
